services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always 
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
    ports:
      - "5430:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
  products-api:
    container_name: products-api
    image: products-api:${TIMESTAMP}
    build:
      dockerfile: './Dockerfile'
      context: '.'
    ports:
      - "8080:8080"
volumes:
  postgresdata: {}

networks:
  products:
    driver: bridge
  